import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final appLocaleProvider = StateProvider<Locale>(
  (ref) => const Locale('pt', 'BR'),
);

Locale localeFromLanguageCode(String code) {
  final parts = code.split('-');
  return parts.length > 1
      ? Locale(parts.first, parts.last)
      : Locale(parts.first);
}

extension AppLocalization on BuildContext {
  String tr(String key) {
    final language = Localizations.localeOf(this).languageCode;
    return _translations[language]?[key] ??
        _screenTranslations[language]?[key] ??
        _translations['pt']![key] ??
        _screenTranslations['pt']![key] ??
        key;
  }

  String categoryLabel(String category) {
    final key = switch (category) {
      'Todos' => 'category.all',
      'Filmes' => 'category.movies',
      'Séries' => 'category.series',
      'Animes' => 'category.anime',
      'Doramas' => 'category.dramas',
      _ => category,
    };
    return tr(key);
  }

  String catalogTitle(String title) {
    final language = Localizations.localeOf(this).languageCode;
    return _catalogTranslations[language]?[title] ?? title;
  }
}

const _translations = <String, Map<String, String>>{
  'pt': {
    'onboarding.welcome': 'Bem-vindo ao CiNey! 👋',
    'onboarding.choose_language':
        'Escolha seu idioma preferido para navegação, legendas e conteúdos.',
    'onboarding.step': 'Passo {current} de {total}',
    'onboarding.installing': 'Instalando e Unificando Catálogo...',
    'onboarding.preparing':
        'Preparando filmes, séries, animes e doramas de todas as fontes selecionadas.',
    'onboarding.back': 'Voltar',
    'onboarding.continue_sources': 'Continuar para Fontes',
    'onboarding.install_watch': 'Instalar & Assistir Agora',
    'onboarding.sources': 'Fontes & Bibliotecas',
    'onboarding.choose_sources':
        'Selecione as extensões. O app unirá tudo em uma só experiência.',
    'onboarding.deselect': 'Desmarcar',
    'onboarding.select_all': 'Selecionar Todas',
    'nav.home': 'Início',
    'nav.search': 'Buscar',
    'nav.profile': 'Perfil',
    'profile.title': 'Ajustes & Perfil',
    'profile.playback': 'Preferências de Reprodução',
    'profile.resume': 'Retomar reprodução',
    'profile.resume_description': 'Continuar do último ponto salvo',
    'profile.autoplay': 'Próximo episódio automaticamente',
    'profile.autoplay_description':
        'Continuar a série quando o episódio terminar',
    'profile.hide_controls': 'Ocultar controles automaticamente',
    'profile.hide_controls_description':
        'Esconder após alguns segundos sem interação',
    'profile.low_bandwidth': 'Modo Poucos Megabits (Conexão Lenta)',
    'profile.low_bandwidth_description':
        'Otimiza buffer de vídeo e reduz tráfego de imagens',
    'profile.landscape': 'Player em paisagem',
    'profile.landscape_description': 'Girar o celular durante a reprodução',
    'profile.sources_storage': 'Fontes & Armazenamento',
    'profile.extensions': 'Gerenciar Extensões & Repositórios',
    'profile.extensions_description':
        'Adicionar ou remover fontes de streaming',
    'profile.language_setup': 'Configurar Idioma & Setup',
    'profile.language_setup_description': 'Reabrir assistente de boas-vindas',
    'profile.clear_cache': 'Limpar Cache de Imagens',
    'profile.clear_cache_description':
        'Libera espaço temporário do dispositivo',
    'profile.cache_cleared': 'Cache limpo com sucesso!',
    'profile.diagnostics': 'Diagnóstico & Developer',
    'profile.about': 'Sobre o Aplicativo',
    'profile.check_updates': 'Verificar Atualizações',
    'profile.checking_updates': 'Consultando GitHub Releases...',
    'profile.update_description': 'Verificar se há nova versão do CiNey',
    'profile.logs': 'Console de Logs em Tempo Real',
    'profile.logs_description':
        'Ver eventos de stream, busca, plugins e erros ao vivo',
    'profile.developer': 'Desenvolvido por Neyvan Santos',
    'profile.description':
        'Aplicativo agregador de filmes, séries, animes e doramas com catálogo unificado, reprodução fluida e sistema modular de extensões.',
    'profile.update_failed': 'Não foi possível verificar. Tente novamente.',
    'profile.up_to_date': 'Você já está na versão mais recente! (v{version})',
    'profile.save_failed': 'Não foi possível salvar a preferência.',
    'category.all': 'Todos',
    'category.movies': 'Filmes',
    'category.series': 'Séries',
    'category.anime': 'Animes',
    'category.dramas': 'Doramas',
    'home.empty': 'Nenhum conteúdo disponível nesta categoria',
    'home.reload': 'Recarregar Catálogo',
    'home.discovering': 'Descobrindo novos títulos...',
    'home.continue_watching': 'Continuar Assistindo',
    'home.in_progress': 'Em andamento',
    'home.watch': 'Assistir',
    'home.details': 'Detalhes',
    'home.see_all': 'Ver todos',
    'home.collections': 'Coleções',
    'home.see_all_collections': 'Ver todas',
    'home.collections_unavailable': 'Coleções indisponíveis. Tentar novamente',
    'search.title': 'Buscar',
    'search.hint': 'Buscar filmes, séries, animes...',
    'search.searching': 'Buscando em todo o catálogo...',
    'search.explore': 'Explore o Catálogo CiNey',
    'search.description':
        'Milhões de filmes, séries e animes do TMDB e extensões',
    'search.trending': 'Sugestões em Alta',
    'search.no_results': 'Nenhum resultado para "{query}"',
    'search.no_results_help':
        'Tente buscar pelo nome original, simplificar os termos ou verificar a ortografia.',
    'search.clear': 'Limpar Pesquisa',
    'search.results_count': '{count} título(s) encontrado(s)',
  },
  'en': {
    'onboarding.welcome': 'Welcome to CiNey! 👋',
    'onboarding.choose_language':
        'Choose your preferred language for browsing, subtitles, and content.',
    'onboarding.step': 'Step {current} of {total}',
    'onboarding.installing': 'Setting up your unified catalog...',
    'onboarding.preparing':
        'Preparing movies, series, anime, and dramas from your selected sources.',
    'onboarding.back': 'Back',
    'onboarding.continue_sources': 'Continue to Sources',
    'onboarding.install_watch': 'Install & Start Watching',
    'onboarding.sources': 'Sources & Libraries',
    'onboarding.choose_sources':
        'Choose extensions. The app brings everything together in one experience.',
    'onboarding.deselect': 'Deselect All',
    'onboarding.select_all': 'Select All',
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.profile': 'Profile',
    'profile.title': 'Settings & Profile',
    'profile.playback': 'Playback Preferences',
    'profile.resume': 'Resume playback',
    'profile.resume_description': 'Continue from the last saved position',
    'profile.autoplay': 'Automatically play next episode',
    'profile.autoplay_description': 'Continue the series when an episode ends',
    'profile.hide_controls': 'Automatically hide controls',
    'profile.hide_controls_description':
        'Hide after a few seconds of inactivity',
    'profile.low_bandwidth': 'Data Saver Mode (Slow Connection)',
    'profile.low_bandwidth_description':
        'Optimizes video buffering and reduces image data usage',
    'profile.landscape': 'Landscape player',
    'profile.landscape_description': 'Rotate your phone during playback',
    'profile.sources_storage': 'Sources & Storage',
    'profile.extensions': 'Manage Extensions & Repositories',
    'profile.extensions_description': 'Add or remove streaming sources',
    'profile.language_setup': 'Language & Setup',
    'profile.language_setup_description': 'Reopen the welcome assistant',
    'profile.clear_cache': 'Clear Image Cache',
    'profile.clear_cache_description': 'Free up temporary device storage',
    'profile.cache_cleared': 'Cache cleared successfully!',
    'profile.diagnostics': 'Diagnostics & Developer',
    'profile.about': 'About the App',
    'profile.check_updates': 'Check for Updates',
    'profile.checking_updates': 'Checking GitHub Releases...',
    'profile.update_description': 'Check for a new CiNey version',
    'profile.logs': 'Live Log Console',
    'profile.logs_description':
        'View live streaming, search, plugin, and error events',
    'profile.developer': 'Developed by Neyvan Santos',
    'profile.description':
        'A unified catalog for movies, series, anime, and dramas, with smooth playback and a modular extension system.',
    'profile.update_failed': 'Could not check for updates. Try again.',
    'profile.up_to_date':
        'You are already using the latest version! (v{version})',
    'profile.save_failed': 'Could not save this preference.',
    'category.all': 'All',
    'category.movies': 'Movies',
    'category.series': 'Series',
    'category.anime': 'Anime',
    'category.dramas': 'Dramas',
    'home.empty': 'No content available in this category',
    'home.reload': 'Reload Catalog',
    'home.discovering': 'Finding new titles...',
    'home.continue_watching': 'Continue Watching',
    'home.in_progress': 'In progress',
    'home.watch': 'Watch',
    'home.details': 'Details',
    'home.see_all': 'See all',
    'home.collections': 'Collections',
    'home.see_all_collections': 'See all',
    'home.collections_unavailable': 'Collections unavailable. Try again',
    'search.title': 'Search',
    'search.hint': 'Search movies, series, anime...',
    'search.searching': 'Searching the entire catalog...',
    'search.explore': 'Explore the CiNey Catalog',
    'search.description':
        'Millions of movies, series, and anime from TMDB and extensions',
    'search.trending': 'Trending Suggestions',
    'search.no_results': 'No results for "{query}"',
    'search.no_results_help':
        'Try the original title, simplify your search, or check the spelling.',
    'search.clear': 'Clear Search',
    'search.results_count': '{count} title(s) found',
  },
  'es': {
    'onboarding.welcome': '¡Te damos la bienvenida a CiNey! 👋',
    'onboarding.choose_language':
        'Elige tu idioma preferido para navegar, ver subtítulos y contenido.',
    'onboarding.step': 'Paso {current} de {total}',
    'onboarding.installing': 'Preparando tu catálogo unificado...',
    'onboarding.preparing':
        'Preparando películas, series, anime y dramas de las fuentes seleccionadas.',
    'onboarding.back': 'Volver',
    'onboarding.continue_sources': 'Continuar a Fuentes',
    'onboarding.install_watch': 'Instalar y Ver Ahora',
    'onboarding.sources': 'Fuentes y Bibliotecas',
    'onboarding.choose_sources':
        'Elige las extensiones. La app reúne todo en una sola experiencia.',
    'onboarding.deselect': 'Deseleccionar Todas',
    'onboarding.select_all': 'Seleccionar Todas',
    'nav.home': 'Inicio',
    'nav.search': 'Buscar',
    'nav.profile': 'Perfil',
    'profile.title': 'Ajustes y Perfil',
    'profile.playback': 'Preferencias de Reproducción',
    'profile.resume': 'Reanudar reproducción',
    'profile.resume_description': 'Continuar desde el último punto guardado',
    'profile.autoplay': 'Reproducir el próximo episodio automáticamente',
    'profile.autoplay_description':
        'Continuar la serie cuando termine el episodio',
    'profile.hide_controls': 'Ocultar controles automáticamente',
    'profile.hide_controls_description':
        'Ocultar tras unos segundos de inactividad',
    'profile.low_bandwidth': 'Modo de bajo consumo (Conexión lenta)',
    'profile.low_bandwidth_description':
        'Optimiza el búfer de video y reduce el uso de datos de imágenes',
    'profile.landscape': 'Reproductor horizontal',
    'profile.landscape_description': 'Girar el móvil durante la reproducción',
    'profile.sources_storage': 'Fuentes y Almacenamiento',
    'profile.extensions': 'Administrar Extensiones y Repositorios',
    'profile.extensions_description': 'Agregar o quitar fuentes de streaming',
    'profile.language_setup': 'Idioma y Configuración',
    'profile.language_setup_description':
        'Volver a abrir el asistente de bienvenida',
    'profile.clear_cache': 'Borrar Caché de Imágenes',
    'profile.clear_cache_description':
        'Liberar espacio temporal del dispositivo',
    'profile.cache_cleared': '¡Caché borrada correctamente!',
    'profile.diagnostics': 'Diagnóstico y Desarrollo',
    'profile.about': 'Acerca de la Aplicación',
    'profile.check_updates': 'Buscar Actualizaciones',
    'profile.checking_updates': 'Consultando GitHub Releases...',
    'profile.update_description': 'Buscar una nueva versión de CiNey',
    'profile.logs': 'Consola de Registros en Vivo',
    'profile.logs_description':
        'Ver eventos de streaming, búsqueda, plugins y errores',
    'profile.developer': 'Desarrollado por Neyvan Santos',
    'profile.description':
        'Catálogo unificado de películas, series, anime y dramas, con reproducción fluida y extensiones modulares.',
    'profile.update_failed': 'No se pudo comprobar. Inténtalo de nuevo.',
    'profile.up_to_date': 'Ya tienes la versión más reciente (v{version})',
    'profile.save_failed': 'No se pudo guardar la preferencia.',
    'category.all': 'Todos',
    'category.movies': 'Películas',
    'category.series': 'Series',
    'category.anime': 'Anime',
    'category.dramas': 'Dramas',
    'home.empty': 'No hay contenido disponible en esta categoría',
    'home.reload': 'Recargar Catálogo',
    'home.discovering': 'Buscando nuevos títulos...',
    'home.continue_watching': 'Seguir Viendo',
    'home.in_progress': 'En curso',
    'home.watch': 'Ver',
    'home.details': 'Detalles',
    'home.see_all': 'Ver todos',
    'home.collections': 'Colecciones',
    'home.see_all_collections': 'Ver todas',
    'home.collections_unavailable':
        'Colecciones no disponibles. Intentar de nuevo',
    'search.title': 'Buscar',
    'search.hint': 'Buscar películas, series, anime...',
    'search.searching': 'Buscando en todo el catálogo...',
    'search.explore': 'Explora el Catálogo CiNey',
    'search.description':
        'Millones de películas, series y anime de TMDB y extensiones',
    'search.trending': 'Sugerencias Populares',
    'search.no_results': 'No hay resultados para "{query}"',
    'search.no_results_help':
        'Prueba con el título original, simplifica la búsqueda o revisa la ortografía.',
    'search.clear': 'Limpiar Búsqueda',
    'search.results_count': '{count} título(s) encontrado(s)',
  },
};

const _screenTranslations = <String, Map<String, String>>{
  'pt': {
    'auth.title_login': 'Entrar no CiNey',
    'auth.title_signup': 'Criar sua conta',
    'auth.title_confirm': 'Confirmar e-mail',
    'auth.title_recover': 'Recuperar senha',
    'auth.title_new_password': 'Escolher nova senha',
    'auth.back_options': 'Voltar para opções',
    'auth.unavailable': 'Contas ainda indisponíveis',
    'auth.unavailable_description':
        'Você precisa entrar na sua conta para usar o CiNey. Reabra o app para tentar novamente.',
    'auth.tv_welcome': 'Bem-vindo ao CiNey na TV',
    'auth.tv_choose':
        'Escolha como deseja se conectar para acessar seus filmes e séries:',
    'auth.recommended': 'RECOMENDADO',
    'auth.qr_title': 'Entrar via QR Code',
    'auth.qr_description':
        'Abra o CiNey no celular (Perfil > Conectar TV) e escaneie a tela para entrar instantaneamente sem digitar.',
    'auth.connect_android': 'Conectar com Android',
    'auth.manual_title': 'Entrar manualmente',
    'auth.manual_description':
        'Digite seu e-mail e senha diretamente na TV usando as teclas do controle remoto.',
    'auth.enter_credentials': 'Digitar dados de acesso',
    'auth.back_qr': 'Voltar para opções (QR Code)',
    'auth.intro_account': 'Crie sua conta ou entre para usar o CiNey.',
    'auth.intro_favorites': 'Seus favoritos no celular e na TV.',
    'auth.name': 'Nome',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.new_password': 'Nova senha',
    'auth.show_password': 'Mostrar senha',
    'auth.hide_password': 'Ocultar senha',
    'auth.password_required': 'Informe sua senha.',
    'auth.confirm_password': 'Confirmar senha',
    'auth.passwords_mismatch': 'As senhas precisam ser iguais.',
    'auth.email_code': 'Código recebido por e-mail',
    'auth.enter_code': 'Digite o código recebido.',
    'auth.notice_confirm':
        'Confira seu e-mail e digite o código de confirmação.',
    'auth.notice_recovery':
        'Se houver uma conta com esse e-mail, você receberá um código.',
    'auth.password_updated': 'Senha atualizada.',
    'auth.notice_email_confirm':
        'Confirme seu e-mail. Se precisar, solicite um novo código.',
    'auth.notice_resend':
        'Se o e-mail estiver correto e elegível, um novo código será enviado.',
    'auth.login': 'Entrar',
    'auth.create_account': 'Criar conta',
    'auth.confirm_code': 'Confirmar código',
    'auth.send_code': 'Enviar código',
    'auth.save_password': 'Salvar nova senha',
    'auth.forgot_password': 'Esqueci minha senha',
    'auth.resend_code': 'Reenviar código',
    'auth.have_account': 'Já tenho uma conta',
    'auth.back_login': 'Voltar para entrar',
    'player.watch_mobile': 'Assistir no Celular',
    'player.settings': 'Configurações de Reprodução',
    'player.settings_help': 'Ajuste qualidade, áudio, legendas e exibição',
    'player.quality.title': 'Qualidade de Vídeo',
    'player.quality.modal': 'Qualidade de Reprodução',
    'player.quality.help': 'Escolha a resolução desejada para transmissão',
    'player.quality.set': 'Qualidade definida para: {value}',
    'player.quality.auto': 'Automática',
    'player.quality.auto_help': 'Adapta à conexão',
    'player.quality.fhd': '1080p FHD',
    'player.quality.fhd_help': 'Alta definição máxima',
    'player.quality.hd': '720p HD',
    'player.quality.hd_help': 'Equilibrado e rápido',
    'player.quality.sd': '480p SD',
    'player.quality.sd_help': 'Economia de dados',
    'player.audio.title': 'Áudio & Idioma',
    'player.audio.modal': 'Áudio e Dublagem',
    'player.audio.help': 'Selecione a trilha sonora e idioma de áudio',
    'player.audio.set': 'Áudio definido para: {value}',
    'player.audio.ptBrDubbed': 'Português (Dublado)',
    'player.audio.ptBrDubbed_help': 'Áudio em Português Brasil',
    'player.audio.ptBrSubtitled': 'Português (Legendado)',
    'player.audio.ptBrSubtitled_help': 'Áudio original com legenda PT-BR',
    'player.audio.original': 'Original',
    'player.audio.original_help': 'Áudio original sem modificações',
    'player.audio.english': 'Inglês (Original)',
    'player.audio.english_help': 'Áudio em Inglês',
    'player.subtitle.title': 'Legendas',
    'player.subtitle.help': 'Ative ou desative legendas sincronizadas',
    'player.subtitle.set': 'Legendas: {value}',
    'player.subtitle.badge_off': 'Sem Legenda',
    'player.subtitle.badge': 'Legenda {value}',
    'player.subtitle.off': 'Desativadas',
    'player.subtitle.off_help': 'Nenhuma legenda visível',
    'player.subtitle.ptBr': 'Português (BR)',
    'player.subtitle.ptBr_help': 'Legendas em Português do Brasil',
    'player.subtitle.english': 'Inglês (EN)',
    'player.subtitle.english_help': 'Legendas em Inglês',
    'player.subtitle.spanish': 'Espanhol (ES)',
    'player.subtitle.spanish_help': 'Legendas em Espanhol',
    'player.server.title': 'Servidores & Fontes',
    'player.server.default': 'Padrão',
    'player.server.modal': 'Servidores de Transmissão',
    'player.server.help': 'Servidores dublados são priorizados automaticamente',
    'player.server.dubbed': 'Áudio Dublado PT-BR • {quality}',
    'player.server.subtitled': 'Áudio Original + Legendas • {quality}',
    'player.server.mixed': 'Múltiplas opções de áudio • {quality}',
    'player.cast.title': 'Transmitir para Smart TV',
    'player.cast.connected': 'Conectado a {device}',
    'player.cast.mirror': 'Espelhar com Chromecast / Navegador',
    'player.aspect.title': 'Proporção da Tela',
    'player.aspect.modal': 'Formato e Proporção',
    'player.aspect.help':
        'Ajuste como o vídeo se adapta à tela do seu aparelho',
    'player.aspect.standard': '16:9 Padrão',
    'player.aspect.standard_help': 'Proporção original de cinema',
    'player.aspect.fitScreen': 'Ajustar à Tela',
    'player.aspect.fill': 'Preencher Tela',
    'player.aspect.fill_help': 'Preenchimento sem bordas pretas',
    'player.reload': 'Recarregar Player',
    'detail.failed': 'Não foi possível carregar os detalhes do título.',
    'detail.retry': 'Tentar novamente',
    'detail.synopsis': 'Sinopse',
    'detail.collection': 'Coleção',
    'detail.episodes': 'Episódios',
    'detail.season': 'Temporada {number}',
    'detail.no_episodes': 'Nenhum episódio disponível nesta temporada.',
  },
  'en': {
    'auth.title_login': 'Sign in to CiNey',
    'auth.title_signup': 'Create your account',
    'auth.title_confirm': 'Confirm email',
    'auth.title_recover': 'Recover password',
    'auth.title_new_password': 'Choose a new password',
    'auth.back_options': 'Back to options',
    'auth.unavailable': 'Accounts are currently unavailable',
    'auth.unavailable_description':
        'You need to sign in to use CiNey. Reopen the app to try again.',
    'auth.tv_welcome': 'Welcome to CiNey on TV',
    'auth.tv_choose': 'Choose how to connect to access your movies and series:',
    'auth.recommended': 'RECOMMENDED',
    'auth.qr_title': 'Sign in with QR Code',
    'auth.qr_description':
        'Open CiNey on your phone (Profile > Connect TV) and scan the screen to sign in instantly.',
    'auth.connect_android': 'Connect with Android',
    'auth.manual_title': 'Sign in manually',
    'auth.manual_description':
        'Enter your email and password on the TV using your remote control.',
    'auth.enter_credentials': 'Enter sign-in details',
    'auth.back_qr': 'Back to options (QR Code)',
    'auth.intro_account': 'Create an account or sign in to use CiNey.',
    'auth.intro_favorites': 'Your favorites on your phone and TV.',
    'auth.name': 'Name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.new_password': 'New password',
    'auth.show_password': 'Show password',
    'auth.hide_password': 'Hide password',
    'auth.password_required': 'Enter your password.',
    'auth.confirm_password': 'Confirm password',
    'auth.passwords_mismatch': 'Passwords do not match.',
    'auth.email_code': 'Code received by email',
    'auth.enter_code': 'Enter the code you received.',
    'auth.notice_confirm': 'Check your email and enter the confirmation code.',
    'auth.notice_recovery':
        'If an account exists for this email, you will receive a code.',
    'auth.password_updated': 'Password updated.',
    'auth.notice_email_confirm':
        'Confirm your email. Request a new code if needed.',
    'auth.notice_resend': 'If the email is valid, a new code will be sent.',
    'auth.login': 'Sign in',
    'auth.create_account': 'Create account',
    'auth.confirm_code': 'Confirm code',
    'auth.send_code': 'Send code',
    'auth.save_password': 'Save new password',
    'auth.forgot_password': 'Forgot password',
    'auth.resend_code': 'Resend code',
    'auth.have_account': 'I already have an account',
    'auth.back_login': 'Back to sign in',
    'player.watch_mobile': 'Watch on Phone',
    'player.settings': 'Playback Settings',
    'player.settings_help': 'Adjust quality, audio, subtitles, and display',
    'player.quality.title': 'Video Quality',
    'player.quality.modal': 'Playback Quality',
    'player.quality.help': 'Choose the streaming resolution',
    'player.quality.set': 'Quality set to: {value}',
    'player.quality.auto': 'Auto',
    'player.quality.auto_help': 'Adapts to your connection',
    'player.quality.fhd': '1080p FHD',
    'player.quality.fhd_help': 'Maximum high definition',
    'player.quality.hd': '720p HD',
    'player.quality.hd_help': 'Balanced and fast',
    'player.quality.sd': '480p SD',
    'player.quality.sd_help': 'Save data',
    'player.audio.title': 'Audio & Language',
    'player.audio.modal': 'Audio & Dubbing',
    'player.audio.help': 'Choose the soundtrack and audio language',
    'player.audio.set': 'Audio set to: {value}',
    'player.audio.ptBrDubbed': 'Portuguese (Dubbed)',
    'player.audio.ptBrDubbed_help': 'Brazilian Portuguese audio',
    'player.audio.ptBrSubtitled': 'Portuguese (Subtitled)',
    'player.audio.ptBrSubtitled_help': 'Original audio with PT-BR subtitles',
    'player.audio.original': 'Original',
    'player.audio.original_help': 'Original audio, unchanged',
    'player.audio.english': 'English (Original)',
    'player.audio.english_help': 'English audio',
    'player.subtitle.title': 'Subtitles',
    'player.subtitle.help': 'Turn synchronized subtitles on or off',
    'player.subtitle.set': 'Subtitles: {value}',
    'player.subtitle.badge_off': 'No Subtitles',
    'player.subtitle.badge': 'Subtitles {value}',
    'player.subtitle.off': 'Off',
    'player.subtitle.off_help': 'No subtitles shown',
    'player.subtitle.ptBr': 'Portuguese (BR)',
    'player.subtitle.ptBr_help': 'Brazilian Portuguese subtitles',
    'player.subtitle.english': 'English (EN)',
    'player.subtitle.english_help': 'English subtitles',
    'player.subtitle.spanish': 'Spanish (ES)',
    'player.subtitle.spanish_help': 'Spanish subtitles',
    'player.server.title': 'Servers & Sources',
    'player.server.default': 'Default',
    'player.server.modal': 'Streaming Servers',
    'player.server.help': 'Dubbed servers are prioritized automatically',
    'player.server.dubbed': 'PT-BR Dubbed Audio • {quality}',
    'player.server.subtitled': 'Original Audio + Subtitles • {quality}',
    'player.server.mixed': 'Multiple audio options • {quality}',
    'player.cast.title': 'Cast to Smart TV',
    'player.cast.connected': 'Connected to {device}',
    'player.cast.mirror': 'Mirror with Chromecast / Browser',
    'player.aspect.title': 'Aspect Ratio',
    'player.aspect.modal': 'Format & Aspect Ratio',
    'player.aspect.help': 'Adjust how video fits your screen',
    'player.aspect.standard': '16:9 Standard',
    'player.aspect.standard_help': 'Original cinema aspect ratio',
    'player.aspect.fitScreen': 'Fit Screen',
    'player.aspect.fill': 'Fill Screen',
    'player.aspect.fill_help': 'Fill without black bars',
    'player.reload': 'Reload Player',
    'detail.failed': 'Could not load title details.',
    'detail.retry': 'Try again',
    'detail.synopsis': 'Overview',
    'detail.collection': 'Collection',
    'detail.episodes': 'Episodes',
    'detail.season': 'Season {number}',
    'detail.no_episodes': 'No episodes available for this season.',
  },
  'es': {
    'auth.title_login': 'Iniciar sesión en CiNey',
    'auth.title_signup': 'Crear tu cuenta',
    'auth.title_confirm': 'Confirmar correo',
    'auth.title_recover': 'Recuperar contraseña',
    'auth.title_new_password': 'Elegir nueva contraseña',
    'auth.back_options': 'Volver a las opciones',
    'auth.unavailable': 'Las cuentas no están disponibles',
    'auth.unavailable_description':
        'Debes iniciar sesión para usar CiNey. Vuelve a abrir la app para intentarlo.',
    'auth.tv_welcome': 'Te damos la bienvenida a CiNey en TV',
    'auth.tv_choose':
        'Elige cómo conectarte para acceder a tus películas y series:',
    'auth.recommended': 'RECOMENDADO',
    'auth.qr_title': 'Iniciar sesión con QR',
    'auth.qr_description':
        'Abre CiNey en el móvil (Perfil > Conectar TV) y escanea la pantalla para entrar al instante.',
    'auth.connect_android': 'Conectar con Android',
    'auth.manual_title': 'Iniciar sesión manualmente',
    'auth.manual_description':
        'Escribe tu correo y contraseña en la TV con las teclas del control remoto.',
    'auth.enter_credentials': 'Ingresar datos de acceso',
    'auth.back_qr': 'Volver a opciones (código QR)',
    'auth.intro_account': 'Crea una cuenta o inicia sesión para usar CiNey.',
    'auth.intro_favorites': 'Tus favoritos en el móvil y en la TV.',
    'auth.name': 'Nombre',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.new_password': 'Nueva contraseña',
    'auth.show_password': 'Mostrar contraseña',
    'auth.hide_password': 'Ocultar contraseña',
    'auth.password_required': 'Ingresa tu contraseña.',
    'auth.confirm_password': 'Confirmar contraseña',
    'auth.passwords_mismatch': 'Las contraseñas no coinciden.',
    'auth.email_code': 'Código recibido por correo',
    'auth.enter_code': 'Ingresa el código recibido.',
    'auth.notice_confirm':
        'Revisa tu correo e ingresa el código de confirmación.',
    'auth.notice_recovery':
        'Si existe una cuenta con este correo, recibirás un código.',
    'auth.password_updated': 'Contraseña actualizada.',
    'auth.notice_email_confirm':
        'Confirma tu correo. Si hace falta, solicita otro código.',
    'auth.notice_resend': 'Si el correo es válido, se enviará un nuevo código.',
    'auth.login': 'Iniciar sesión',
    'auth.create_account': 'Crear cuenta',
    'auth.confirm_code': 'Confirmar código',
    'auth.send_code': 'Enviar código',
    'auth.save_password': 'Guardar nueva contraseña',
    'auth.forgot_password': 'Olvidé mi contraseña',
    'auth.resend_code': 'Reenviar código',
    'auth.have_account': 'Ya tengo una cuenta',
    'auth.back_login': 'Volver a iniciar sesión',
    'player.watch_mobile': 'Ver en el móvil',
    'player.settings': 'Ajustes de Reproducción',
    'player.settings_help': 'Ajusta calidad, audio, subtítulos y pantalla',
    'player.quality.title': 'Calidad de Video',
    'player.quality.modal': 'Calidad de Reproducción',
    'player.quality.help': 'Elige la resolución de transmisión',
    'player.quality.set': 'Calidad establecida en: {value}',
    'player.quality.auto': 'Automática',
    'player.quality.auto_help': 'Se adapta a tu conexión',
    'player.quality.fhd': '1080p FHD',
    'player.quality.fhd_help': 'Máxima alta definición',
    'player.quality.hd': '720p HD',
    'player.quality.hd_help': 'Equilibrado y rápido',
    'player.quality.sd': '480p SD',
    'player.quality.sd_help': 'Ahorro de datos',
    'player.audio.title': 'Audio e Idioma',
    'player.audio.modal': 'Audio y Doblaje',
    'player.audio.help': 'Elige la banda sonora y el idioma de audio',
    'player.audio.set': 'Audio establecido en: {value}',
    'player.audio.ptBrDubbed': 'Portugués (Doblado)',
    'player.audio.ptBrDubbed_help': 'Audio en portugués brasileño',
    'player.audio.ptBrSubtitled': 'Portugués (Subtitulado)',
    'player.audio.ptBrSubtitled_help': 'Audio original con subtítulos PT-BR',
    'player.audio.original': 'Original',
    'player.audio.original_help': 'Audio original sin modificaciones',
    'player.audio.english': 'Inglés (Original)',
    'player.audio.english_help': 'Audio en inglés',
    'player.subtitle.title': 'Subtítulos',
    'player.subtitle.help': 'Activa o desactiva los subtítulos sincronizados',
    'player.subtitle.set': 'Subtítulos: {value}',
    'player.subtitle.badge_off': 'Sin subtítulos',
    'player.subtitle.badge': 'Subtítulos {value}',
    'player.subtitle.off': 'Desactivados',
    'player.subtitle.off_help': 'No se muestran subtítulos',
    'player.subtitle.ptBr': 'Portugués (BR)',
    'player.subtitle.ptBr_help': 'Subtítulos en portugués brasileño',
    'player.subtitle.english': 'Inglés (EN)',
    'player.subtitle.english_help': 'Subtítulos en inglés',
    'player.subtitle.spanish': 'Español (ES)',
    'player.subtitle.spanish_help': 'Subtítulos en español',
    'player.server.title': 'Servidores y Fuentes',
    'player.server.default': 'Predeterminado',
    'player.server.modal': 'Servidores de Transmisión',
    'player.server.help':
        'Los servidores doblados se priorizan automáticamente',
    'player.server.dubbed': 'Audio doblado PT-BR • {quality}',
    'player.server.subtitled': 'Audio original + subtítulos • {quality}',
    'player.server.mixed': 'Varias opciones de audio • {quality}',
    'player.cast.title': 'Transmitir a Smart TV',
    'player.cast.connected': 'Conectado a {device}',
    'player.cast.mirror': 'Duplicar con Chromecast / Navegador',
    'player.aspect.title': 'Relación de Aspecto',
    'player.aspect.modal': 'Formato y Proporción',
    'player.aspect.help': 'Ajusta cómo se adapta el video a tu pantalla',
    'player.aspect.standard': '16:9 Estándar',
    'player.aspect.standard_help': 'Proporción cinematográfica original',
    'player.aspect.fitScreen': 'Ajustar a la Pantalla',
    'player.aspect.fill': 'Llenar Pantalla',
    'player.aspect.fill_help': 'Llenar sin bordes negros',
    'player.reload': 'Recargar Reproductor',
    'detail.failed': 'No se pudieron cargar los detalles del título.',
    'detail.retry': 'Intentar de nuevo',
    'detail.synopsis': 'Sinopsis',
    'detail.collection': 'Colección',
    'detail.episodes': 'Episodios',
    'detail.season': 'Temporada {number}',
    'detail.no_episodes': 'No hay episodios disponibles en esta temporada.',
  },
};

const _catalogTranslations = <String, Map<String, String>>{
  'en': {
    'Favoritos': 'Favorites',
    'Lançamentos': 'New Releases',
    'Em Alta': 'Trending',
    'Lançamentos em Filmes': 'New Movies',
    'Filmes em Alta': 'Trending Movies',
    'Lançamentos em Séries': 'New Series',
    'Séries em Alta': 'Trending Series',
    'Animes em Destaque': 'Featured Anime',
    'Doramas em Destaque': 'Featured Dramas',
    'Filmes de Ação & Pura Adrenalina': 'Action Movies & Pure Adrenaline',
    'Séries Mais Assistidas': 'Most Watched Series',
    'Comédias Imperdíveis': 'Must-See Comedies',
    'Ficção Científica & Futuro': 'Science Fiction & the Future',
    'Suspense & Mistério': 'Thrillers & Mystery',
    'Doramas Coreanos Favoritos': 'Favorite Korean Dramas',
    'Aventura & Fantasia': 'Adventure & Fantasy',
    'Terror & Sobrenatural': 'Horror & Supernatural',
    'Séries Policiais & Investigação': 'Crime & Investigation Series',
    'Animações para Toda Família': 'Animation for the Whole Family',
    'Dramas Aclamados pela Crítica': 'Critically Acclaimed Dramas',
    'Séries de Mistério & Ficção': 'Mystery & Sci-Fi Series',
    'Romances Apaixonantes': 'Captivating Romance',
    'Documentários & Histórias Reais': 'Documentaries & True Stories',
    'Clássicos Inesquecíveis': 'Unforgettable Classics',
    'Filmes de Ação Explosiva': 'Explosive Action Movies',
    'Comédias Divertidas': 'Fun Comedies',
    'Ficção Científica & Espaço': 'Science Fiction & Space',
    'Suspense Eletrizante': 'Electrifying Thrillers',
    'Terror de Arrepiar': 'Chilling Horror',
    'Aventura & Exploração': 'Adventure & Exploration',
    'Mundos Mágicos & Fantasia': 'Magical Worlds & Fantasy',
    'Animações Cinematográficas': 'Cinematic Animation',
    'Dramas Profundos & Emocionantes': 'Moving, Deep Dramas',
    'Romances Apaixonados': 'Passionate Romance',
    'Guerra & Batalhas Épicas': 'War & Epic Battles',
    'Filmes Mais Bem Avaliados': 'Top-Rated Movies',
    'Clássicos de Ouro do Cinema': 'Golden Cinema Classics',
    'Séries do Momento': 'Popular Series Now',
    'Séries de Ação & Aventura': 'Action & Adventure Series',
    'Dramas Envolventes & Premiados': 'Engaging, Award-Winning Dramas',
    'Mistério & Ficção Científica': 'Mystery & Science Fiction',
    'Comédias & Sitcoms': 'Comedies & Sitcoms',
    'Séries Policiais & Crimes Reais': 'Crime & True Crime Series',
    'Séries Documentais': 'Documentary Series',
    'Séries Mais Bem Avaliadas': 'Top-Rated Series',
    'Animes Populares no Japão': 'Popular Anime in Japan',
    'Animes de Ação & Batalhas Épicas': 'Action Anime & Epic Battles',
    'Animes de Fantasia & Isekai': 'Fantasy & Isekai Anime',
    'Comédias & Vida Cotidiana em Anime': 'Anime Comedy & Everyday Life',
    'Filmes em Anime': 'Anime Movies',
    'Animes Mais Bem Avaliados': 'Top-Rated Anime',
    'K-Dramas Românticos Mais Amados': 'Beloved Romantic K-Dramas',
    'Dramas Coreanos Emocionantes': 'Moving Korean Dramas',
    'Comédias Românticas Coreanas': 'Korean Romantic Comedies',
    'Doramas de Suspense & Investigação': 'Thriller & Crime Dramas',
    'Doramas Populares do Momento': 'Popular Dramas Now',
    'Doramas Aclamados pelo Público': 'Audience-Favorite Dramas',
  },
  'es': {
    'Favoritos': 'Favoritos',
    'Lançamentos': 'Estrenos',
    'Em Alta': 'Tendencias',
    'Lançamentos em Filmes': 'Estrenos de Películas',
    'Filmes em Alta': 'Películas Populares',
    'Lançamentos em Séries': 'Estrenos de Series',
    'Séries em Alta': 'Series Populares',
    'Animes em Destaque': 'Anime Destacado',
    'Doramas em Destaque': 'Dramas Destacados',
    'Filmes de Ação & Pura Adrenalina': 'Acción y Pura Adrenalina',
    'Séries Mais Assistidas': 'Series Más Vistas',
    'Comédias Imperdíveis': 'Comedias Imperdibles',
    'Ficção Científica & Futuro': 'Ciencia Ficción y Futuro',
    'Suspense & Mistério': 'Suspenso y Misterio',
    'Doramas Coreanos Favoritos': 'Dramas Coreanos Favoritos',
    'Aventura & Fantasia': 'Aventura y Fantasía',
    'Terror & Sobrenatural': 'Terror y Sobrenatural',
    'Séries Policiais & Investigação': 'Series Policiales e Investigación',
    'Animações para Toda Família': 'Animación para Toda la Familia',
    'Dramas Aclamados pela Crítica': 'Dramas Aclamados por la Crítica',
    'Séries de Mistério & Ficção': 'Series de Misterio y Ciencia Ficción',
    'Romances Apaixonantes': 'Romances Apasionantes',
    'Documentários & Histórias Reais': 'Documentales e Historias Reales',
    'Clássicos Inesquecíveis': 'Clásicos Inolvidables',
    'Filmes de Ação Explosiva': 'Películas de Acción Explosiva',
    'Comédias Divertidas': 'Comedias Divertidas',
    'Ficção Científica & Espaço': 'Ciencia Ficción y Espacio',
    'Suspense Eletrizante': 'Suspenso Electrizante',
    'Terror de Arrepiar': 'Terror Escalofriante',
    'Aventura & Exploração': 'Aventura y Exploración',
    'Mundos Mágicos & Fantasia': 'Mundos Mágicos y Fantasía',
    'Animações Cinematográficas': 'Animación Cinematográfica',
    'Dramas Profundos & Emocionantes': 'Dramas Profundos y Emocionantes',
    'Romances Apaixonados': 'Romances Apasionados',
    'Guerra & Batalhas Épicas': 'Guerra y Batallas Épicas',
    'Filmes Mais Bem Avaliados': 'Películas Mejor Valoradas',
    'Clássicos de Ouro do Cinema': 'Clásicos de Oro del Cine',
    'Séries do Momento': 'Series del Momento',
    'Séries de Ação & Aventura': 'Series de Acción y Aventura',
    'Dramas Envolventes & Premiados': 'Dramas Cautivadores y Premiados',
    'Mistério & Ficção Científica': 'Misterio y Ciencia Ficción',
    'Comédias & Sitcoms': 'Comedias y Sitcoms',
    'Séries Policiais & Crimes Reais': 'Series Policiales y Crímenes Reales',
    'Séries Documentais': 'Series Documentales',
    'Séries Mais Bem Avaliadas': 'Series Mejor Valoradas',
    'Animes Populares no Japão': 'Anime Popular en Japón',
    'Animes de Ação & Batalhas Épicas': 'Anime de Acción y Batallas Épicas',
    'Animes de Fantasia & Isekai': 'Anime de Fantasía e Isekai',
    'Comédias & Vida Cotidiana em Anime':
        'Comedia y Vida Cotidiana en el Anime',
    'Filmes em Anime': 'Películas de Anime',
    'Animes Mais Bem Avaliados': 'Anime Mejor Valorado',
    'K-Dramas Românticos Mais Amados': 'K-Dramas Románticos Más Queridos',
    'Dramas Coreanos Emocionantes': 'Dramas Coreanos Emocionantes',
    'Comédias Românticas Coreanas': 'Comedias Románticas Coreanas',
    'Doramas de Suspense & Investigação': 'Dramas de Suspenso e Investigación',
    'Doramas Populares do Momento': 'Dramas Populares del Momento',
    'Doramas Aclamados pelo Público': 'Dramas Favoritos del Público',
  },
};
